---
 - name: Elk Playbook
   hosts: elk
   become: true
   tasks: 
        - name: use more memory
          sysctl:
           name: vm.max_map_count
           value: '262144'
           state: present
           reload: yes
   
        - name: Install Docker
          apt:
             force_apt_get: yes
             update_cache: yes
             name: docker.io
             state: present
        
        - name: Install pip3
          apt:
             force_apt_get: yes
             name: python3-pip
             state: present
        
        - name: Install Docker module
          pip: 
            name: docker
            state: present

   
        - name: Web conatainer
          docker_container: 
             name: elk
             image: sebp/elk:761
             state: started
             restart_policy: always
             published_ports: 
                          - 5601:5601
          


        - name: Web conatainer
          docker_container: 
             name: elk
             image: sebp/elk:761
             state: started
             restart_policy: always
             published_ports:                 
                         -  9200:9200



        - name: Web conatainer
          docker_container: 
             name: elk
             image: sebp/elk:761
             state: started
             restart_policy: always
             published_ports:
                         - 5044:5044
